/**
 * DDL DO SISTEMA GERENCIADOR DE PEDIDOS
 *
 * Autor: Guilherme França
 * Data: 10/07/2018
 */
CREATE TABLE [dbo].[STATUS] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[DESCRICAO] VARCHAR(20) NOT NULL
);

CREATE TABLE [dbo].[FORMA_RECEBIMENTO] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[DESCRICAO] VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[FORMA_REMESSA] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[DESCRICAO] VARCHAR(30) NOT NULL
);

CREATE TABLE [dbo].[TIPO_USUARIO] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[DESCRICAO] VARCHAR(10) NOT NULL
);

CREATE TABLE [dbo].[PEDIDO] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[NUMERO] INT NOT NULL UNIQUE,
	[REMESSA_CORREIO] DATETIME,
	[ENDERECO] VARCHAR(200) NOT NULL,
	[TELEFONE] VARCHAR(15),
	[EMAIL] VARCHAR(60),
	[DATA_PEDIDO] DATETIME NOT NULL DEFAULT GETDATE(),
	[DATA_ATENDIMENTO] DATETIME NOT NULL DEFAULT GETDATE(),
	[DOCUMENTOS] TEXT NOT NULL,
	[VALOR] DECIMAL(9, 2) NOT NULL,
	[DOCUMENTALISTA] VARCHAR(50) NOT NULL,
	[OBSERVACOES] VARCHAR(255),
	[EXCLUIDO] TINYINT NOT NULL DEFAULT 0,
	[STATUS] INT NOT NULL CONSTRAINT PEDIDO_STATUS_FK 
						  FOREIGN KEY REFERENCES [STATUS]([CODIGO]),

	[FORMA_RECEBIMENTO] INT NOT NULL CONSTRAINT PEDIDO_FORMA_RECEBIMENTO_FK 
									 FOREIGN KEY REFERENCES [FORMA_RECEBIMENTO]([CODIGO]),

	[FORMA_REMESSA] INT NOT NULL CONSTRAINT PEDIDO_FORMA_REMESSA_FK 
							     FOREIGN KEY REFERENCES [FORMA_REMESSA]([CODIGO]),

	[TIPO_USUARIO] INT NOT NULL CONSTRAINT PEDIDO_TIPO_USUARIO_FK 
							    FOREIGN KEY REFERENCES [TIPO_USUARIO]([CODIGO])
);

CREATE TABLE [dbo].[PERFIL] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[INCLUSAO] TINYINT NOT NULL DEFAULT 0,
	[ALTERACAO] TINYINT NOT NULL DEFAULT 0,
	[DUPLICACAO] TINYINT NOT NULL DEFAULT 0,
	[EXCLUSAO] TINYINT NOT NULL DEFAULT 0,
	[GERENCIAPERFIS] TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE [dbo].[OPERADOR] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[NOME] VARCHAR(100) NOT NULL,
	[RAMAL] VARCHAR(20),
	[IDENTIFICACAO] VARCHAR(20) NOT NULL UNIQUE,
	[SENHA] VARCHAR(16) NOT NULL,
	[PERFIL] INT NOT NULL CONSTRAINT OPERADOR_PERFIL_FK
						  FOREIGN KEY REFERENCES [PERFIL]([CODIGO])
);

CREATE TABLE [dbo].[ACAO] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[DESCRICAO] VARCHAR(200) NOT NULL
);

CREATE TABLE [dbo].[HISTORICO_PEDIDO] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[DATA_FATO] DATETIME NOT NULL DEFAULT GETDATE(),
	[PEDIDO] INT NOT NULL CONSTRAINT HISTORICO_PEDIDO_FK
						  FOREIGN KEY REFERENCES [PEDIDO]([CODIGO]),

	[OPERADOR] INT NOT NULL CONSTRAINT HISTORICO_PEDIDO_OPERADOR_FK
							FOREIGN KEY REFERENCES [OPERADOR]([CODIGO])
);

CREATE TABLE [dbo].[HISTORICO_PEDIDO_ACAO] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[HISTORICO_PEDIDO] INT NOT NULL CONSTRAINT HISTORICO_PEDIDO_ACAO_H_FK
						FOREIGN KEY REFERENCES [HISTORICO_PEDIDO]([CODIGO]),

	[ACAO] INT NOT NULL CONSTRAINT HISTORICO_PEDIDO_ACAO_A_FK
						FOREIGN KEY REFERENCES [ACAO]([CODIGO])
)

CREATE TABLE [dbo].[SEQUENCIA_PEDIDO] (
	[SEQUENCIA] INT NOT NULL
);

CREATE TABLE [dbo].[PESSOA] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[NOME] VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[PEDIDO_PESSOA] (
	[CODIGO] INT PRIMARY KEY IDENTITY(1, 1),
	[PESSOA] INT NOT NULL CONSTRAINT PEDIDO_PESSOA_PS_FK
						  FOREIGN KEY REFERENCES [PESSOA]([CODIGO]),

	[PEDIDO] INT NOT NULL CONSTRAINT PEDIDO_PESSOA_PD_FK
						  FOREIGN KEY REFERENCES [PEDIDO]([CODIGO])
);

/* INCLUSÃO DE DADOS NÃO-DEPENDENTES */
INSERT INTO [dbo].[FORMA_RECEBIMENTO] 
VALUES ('Opções Biblioteca'), ('E-mail'), ('Outros'), ('Secretaria Eletrônica'), ('Telefone');

INSERT INTO [dbo].[FORMA_REMESSA] 
VALUES ('Biblioteca'), ('Correio'), ('Sedex 10'), ('E-mail'), ('Malote');

INSERT INTO [dbo].[TIPO_USUARIO] 
VALUES ('Externo'), ('Interno');

INSERT INTO [dbo].[STATUS]
VALUES ('Atendido'), ('Encaminhado');

INSERT INTO [dbo].[ACAO]
VALUES ('Inclusão de um novo pedido'), 
	   ('Alteração do campo Remessa Correio do pedido'),
	   ('Alteração do Nome do(s) Usuário(s) do pedido'),
	   ('Alteração do Endereço do pedido'),
	   ('Alteração do Telefone do pedido'),
	   ('Alteração do E-mail do pedido'),
	   ('Alteração da Data do pedido'),
	   ('Alteração da Data de Atendimento do pedido'),
	   ('Alteração da Forma de Recebimento do pedido'),
	   ('Alteração de Remessa do pedido'),
	   ('Alteração de um ou mais Documentos do pedido'),
	   ('Alteração das Observações do pedido'),
	   ('Alteração do Documentalista do pedido'),
	   ('Alteração do Tipo de Usuário do pedido'),
	   ('Alteração do Valor do pedido'),
	   ('Exclusão do pedido');

INSERT INTO [dbo].[PERFIL] (INCLUSAO, ALTERACAO, DUPLICACAO, EXCLUSAO, GERENCIAPERFIS)
VALUES (1, 1, 1, 1, 1)

INSERT INTO [dbo].[OPERADOR] (NOME, IDENTIFICACAO, SENHA, PERFIL)
VALUES ('SUPERVISOR', 'SUPERVISOR', 'M@sterkey', (SELECT MAX(CODIGO) FROM [dbo].[PERFIL]))